import turtle

# Create a screen and a turtle object
screen = turtle.Screen()
screen.bgcolor("#eeeeee")  # Set background color
draw = turtle.Turtle()
draw.speed(10)  # Set drawing speed

# Define functions for drawing curves
def curve1():
    for i in range(95):
        draw.right(1)
        draw.forward(1)

def curve2():
    for i in range(95):
        draw.left(1)
        draw.forward(1)

# Initial setup
draw.hideturtle()
turtle.tracer(5)

# --- Draw Hair ---
draw.pencolor('black')
draw.fillcolor("blue")
draw.begin_fill()
draw.penup()
draw.goto(0, 190)
draw.pendown()
draw.right(25)
draw.forward(60)
draw.left(135)
draw.forward(100)
draw.right(95)
draw.forward(95)
draw.left(135)
draw.forward(118)
draw.right(100)
draw.forward(100)
draw.left(145)
draw.forward(120)
draw.right(90)
draw.forward(60)
draw.left(135)
draw.forward(65)
draw.right(90)
draw.forward(60)
draw.left(135)
draw.forward(65)
draw.right(90)
draw.forward(60)
draw.left(135)
draw.forward(120)
draw.right(100)
draw.forward(100)
draw.left(145)
draw.forward(118)
draw.right(95)
draw.forward(95)
draw.left(135)
draw.forward(100)
draw.right(100)
draw.forward(10)
draw.end_fill()

# --- Draw Face ---
draw.fillcolor('#E8BEAC')
draw.begin_fill()
draw.pensize(8)
draw.left(60)
draw.forward(73)
draw.right(95)
draw.forward(133)
draw.right(40)
draw.forward(80)
draw.right(37)
draw.forward(150)
draw.right(35)
draw.forward(89)
draw.left(89)
draw.forward(32)
draw.right(50)
draw.forward(63)
draw.right(18)
draw.forward(130)
draw.right(10)
draw.forward(63)
draw.right(50)
draw.forward(32)
draw.left(89)
draw.forward(89)
draw.right(35)
draw.forward(150)
draw.right(37)
draw.forward(80)
draw.right(40)
draw.forward(133)
draw.end_fill()

# --- Draw Ears ---
draw.penup()
draw.goto(-148, 20)
draw.pendown()
draw.fillcolor('#E8BEAC')
draw.begin_fill()
draw.right(175)
curve2()
draw.seth(-90)
draw.forward(30)
draw.end_fill()
draw.penup()
draw.goto(152, 20)
draw.pendown()
draw.fillcolor('#E8BEAC')
draw.begin_fill()
draw.seth(0)
curve1()
draw.seth(-90)
draw.forward(30)
draw.end_fill()

# --- Draw Headband ---
draw.penup()
draw.goto(-170, 70)
draw.pendown()
draw.fillcolor('black')
draw.begin_fill()
draw.forward(340)
draw.left(90)
draw.forward(50)
draw.left(90)
draw.forward(340)
draw.left(90)
draw.forward(50)
draw.end_fill()

# --- Draw Headband Plate ---
draw.penup()
draw.goto(-80, 75)
draw.pendown()
draw.fillcolor('silver')
draw.begin_fill()
draw.left(180)
draw.forward(170)
draw.left(80)
draw.forward(40)
draw.left(100)
draw.forward(170)
draw.left(80)
draw.forward(40)
draw.end_fill()

# --- Draw Hidden Leaf Symbol ---
draw.penup()
draw.goto(-35, 80)
draw.pendown()
draw.fillcolor('black')
draw.begin_fill()
draw.pensize(1)
draw.left(150)
draw.forward(40)
draw.right(90)
draw.forward(10)
draw.right(90)
draw.forward(15)
draw.left(90)
draw.forward(15)
draw.right(90)
draw.forward(25)
draw.right(90)
draw.forward(15)
draw.left(90)
draw.forward(15)
draw.right(90)
draw.forward(10)
draw.end_fill()

# Headband screws
draw.penup()
draw.goto(-70, 105)
draw.pendown()
draw.dot(10)
draw.penup()
draw.goto(-70, 85)
draw.pendown()
draw.dot(10)
draw.penup()
draw.goto(75, 105)
draw.pendown()
draw.dot(10)
draw.penup()
draw.goto(75, 85)
draw.pendown()
draw.dot(10)

# --- Draw Eyes (Sharingan) ---
# Right Eye
draw.penup()
draw.goto(100, 20)
draw.pendown()
draw.fillcolor('red')
draw.begin_fill()
draw.right(10)
draw.forward(70)
draw.left(120)
draw.forward(70)
draw.left(120)
draw.forward(70)
draw.end_fill()
draw.penup()
draw.goto(65, 10)
draw.pendown()
draw.dot(20)
# Left Eye
draw.penup()
draw.goto(-40, 20)
draw.pendown()
draw.fillcolor('red')
draw.begin_fill()
draw.right(120)
draw.forward(70)
draw.left(120)
draw.forward(70)
draw.left(120)
draw.forward(70)
draw.end_fill()
draw.penup()
draw.goto(-75, 10)
draw.pendown()
draw.dot(20)

# --- Draw Mouth and Whiskers ---
# Mouth
draw.penup()
draw.goto(-35, -50)
draw.pendown()
draw.right(50)
curve2()
# Whiskers
draw.penup()
draw.goto(90, -20)
draw.pendown()
draw.left(140)
draw.forward(50)
draw.penup()
draw.goto(90, -40)
draw.pendown()
draw.forward(50)
draw.penup()
draw.goto(90, -60)
draw.pendown()
draw.forward(50)
draw.penup()
draw.goto(-90, -20)
draw.pendown()
draw.left(60)
draw.forward(50)
draw.penup()
draw.goto(-90, -40)
draw.pendown()
draw.forward(50)
draw.penup()
draw.goto(-90, -60)
draw.pendown()
draw.forward(50)

turtle.done()